# Generated by Django 4.2.29 on 2026-04-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPSB', '0003_newspostmedia_is_banner_newspostmedia_section_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='media',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
