# Generated by Django 4.2.29 on 2026-04-19 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPSB', '0004_media_alt_text_media_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspostmedia',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SPSB.media'),
        ),
    ]
