# Generated by Django 4.2.29 on 2026-04-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPSB', '0005_alter_newspostmedia_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_hash',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
